`sei la dimostrazione vivente che l'evoluzione può sbagliarsi`,
  `il tuo IQ deve essere un numero negativo`,
  `le tue domande sono come un buco nero di intelligenza`,
  `sei così fuori pista che hai bisogno di un GPS per tornare alla realtà`,
  `probabilmente persino una pianta ha una comprensione migliore del mondo rispetto a te`,
  `sembri essere stato creato in un laboratorio di risate`,
  `il tuo cervello deve essere ancora in fase di installazione`,
  `perché non provi a chiedere al muro? Forse ottieni una risposta più intelligente`,
  `se c'è un premio per la domanda più stupida, penso che tu l'abbia appena vinta`,
  `non capisco nemmeno la tua domanda, ma sono sicuro che è stupida`,
  `la tua domanda ha appena abbassato il QI di tutti quelli che l'hanno letta`,
  `hai mai pensato che la tua domanda potrebbe essere la causa della scomparsa dei dinosauri?`,
  `la tua domanda mi ha fatto desiderare di avere amnesia`,
  `se la tua domanda fosse un film, sarebbe un flop totale al botteghino`,
  `sono sicuro che anche un robot sarebbe più interessante di te`,
  `dopo aver letto la tua domanda, credo di aver bisogno di una terapia`,
  `hai intenzione di proseguire con queste domande, o posso smettere di sperare?`,
  `mi chiedo se nella tua mente ci sia un'eco quando fai una domanda`,
  `la tua domanda ha appena reso più difficile credere nell'umanità`,
  `la tua domanda è come una barzelletta, solo senza la parte divertente`,
  `se la tua domanda fosse una canzone, sarebbe fuori tono`,
  `penso che il tuo cervello abbia bisogno di un aggiornamento`,
  `la tua domanda ha appena abbattuto il record di quanto possa essere banale`,
  `non riesco nemmeno a trovare parole per descrivere quanto sia inutile la tua domanda`,
  `se la tua domanda fosse una valuta, sarebbe la moneta più svalutata al mondo`,
  `non posso decidere se rispondere alla tua domanda sia uno spreco di tempo o una tragedia`,
  `quando hai pensato a quella domanda, hai davvero fatto del tuo meglio?`,
  `spero che tu abbia una buona assicurazione per coprire i danni cerebrali causati dalla tua domanda`,
  `quando è stata l'ultima volta che hai avuto un'idea intelligente?`,
  `la tua domanda mi ha fatto desiderare di avere una lavatrice per il cervello`,
  `se la stupidità fosse un'arte, tu saresti un vero artista`,
  `la tua domanda è come un piccolo pezzo di caos in un mondo già caotico`,
  `hai mai pensato che la tua domanda potrebbe essere l'inizio della fine della tua intelligenza?`,
  `spero che la tua domanda non sia la tua migliore performance, altrimenti mi dispiace per te`,
  `la tua domanda ha appena fatto colare una lacrima a Isaac Newton`,
  `se la tua domanda fosse una medicina, sarebbe classificata come tossica per l'intelligenza`,
  `mi chiedo se la tua domanda sia il risultato di una scommessa persa`,
  `non posso decidere se rispondere alla tua domanda sia uno spreco di tempo o un esercizio di pazienza`,
  `la tua domanda ha appena fatto scappare lo spirito santo dalla mia mente`,
  `hai mai pensato che la tua domanda potrebbe essere la prova che siamo soli nell'universo?`,
  `spero che la tua domanda non sia rappresentativa della tua vita quotidiana, altrimenti mi dispiace per te`,
  `se la tua domanda fosse un romanzo, sarebbe classificato come "fantascienza"`,
  `la tua domanda mi ha fatto desiderare di poter viaggiare indietro nel tempo per evitare che la facessi`,
  `mi dispiace, non sono un mago, non posso rispondere a domande impossibili`,
  `quando hai pensato a quella domanda, hai sentito un suono? Era il rumore del mio cervello implodere`,
  `spero che tu non abbia intenzione di fare domande del genere in futuro, altrimenti mi renderai disoccupato`,
  `la tua domanda mi ha fatto desiderare di poter cancellare la tua memoria per sempre`,
  `mi chiedo se la tua domanda abbia abbassato la temperatura del mio cervello di qualche grado`,
`sei la dimostrazione vivente che l'evoluzione può sbagliarsi`,
  `il tuo IQ deve essere un numero negativo`,
  `le tue domande sono come un buco nero di intelligenza`,
  `sei così fuori pista che hai bisogno di un GPS per tornare alla realtà`,
  `probabilmente persino una pianta ha una comprensione migliore del mondo rispetto a te`,
  `sembri essere stato creato in un laboratorio di risate`,
  `il tuo cervello deve essere ancora in fase di installazione`,
  `perché non provi a chiedere al muro? Forse ottieni una risposta più intelligente`,
  `se c'è un premio per la domanda più stupida, penso che tu l'abbia appena vinta`,
  `non capisco nemmeno la tua domanda, ma sono sicuro che è stupida`,
  `la tua domanda ha appena abbassato il QI di tutti quelli che l'hanno letta`,
  `hai mai pensato che la tua domanda potrebbe essere la causa della scomparsa dei dinosauri?`,
  `la tua domanda mi ha fatto desiderare di avere amnesia`,
  `se la tua domanda fosse un film, sarebbe un flop totale al botteghino`,
  `sono sicuro che anche un robot sarebbe più interessante di te`,
  `dopo aver letto la tua domanda, credo di aver bisogno di una terapia`,
  `hai intenzione di proseguire con queste domande, o posso smettere di sperare?`,
  `mi chiedo se nella tua mente ci sia un'eco quando fai una domanda`,
  `la tua domanda ha appena reso più difficile credere nell'umanità`,
  `la tua domanda è come una barzelletta, solo senza la parte divertente`,
  `se la tua domanda fosse una canzone, sarebbe fuori tono`,
  `penso che il tuo cervello abbia bisogno di un aggiornamento`,
  `la tua domanda ha appena abbattuto il record di quanto possa essere banale`,
  `non riesco nemmeno a trovare parole per descrivere quanto sia inutile la tua domanda`,
  `se la tua domanda fosse una valuta, sarebbe la moneta più svalutata al mondo`,
  `non posso decidere se rispondere alla tua domanda sia uno spreco di tempo o una tragedia`,
  `quando hai pensato a quella domanda, hai davvero fatto del tuo meglio?`,
  `spero che tu abbia una buona assicurazione per coprire i danni cerebrali causati dalla tua domanda`,
  `quando è stata l'ultima volta che hai avuto un'idea intelligente?`,
  `la tua domanda mi ha fatto desiderare di avere una lavatrice per il cervello`,
  `se la stupidità fosse un'arte, tu saresti un vero artista`,
  `la tua domanda è come un piccolo pezzo di caos in un mondo già caotico`,
  `hai mai pensato che la tua domanda potrebbe essere l'inizio della fine della tua intelligenza?`,
  `spero che la tua domanda non sia la tua migliore performance, altrimenti mi dispiace per te`,
  `la tua domanda ha appena fatto colare una lacrima a Isaac Newton`,
  `se la tua domanda fosse una medicina, sarebbe classificata come tossica per l'intelligenza`,
  `mi chiedo se la tua domanda sia il risultato di una scommessa persa`,
  `non posso decidere se rispondere alla tua domanda sia uno spreco di tempo o un esercizio di pazienza`,
  `la tua domanda ha appena fatto scappare lo spirito santo dalla mia mente`,
  `hai mai pensato che la tua domanda potrebbe essere la prova che siamo soli nell'universo?`,
  `spero che la tua domanda non sia rappresentativa della tua vita quotidiana, altrimenti mi dispiace per te`,
  `se la tua domanda fosse un romanzo, sarebbe classificato come "fantascienza"`,
  `la tua domanda mi ha fatto desiderare di poter viaggiare indietro nel tempo per evitare che la facessi`,
  `mi dispiace, non sono un mago, non posso rispondere a domande impossibili`,
  `quando hai pensato a quella domanda, hai sentito un suono? Era il rumore del mio cervello implodere`,
  `spero che tu non abbia intenzione di fare domande del genere in futuro, altrimenti mi renderai disoccupato`,
  `la tua domanda mi ha fatto desiderare di poter cancellare la tua memoria per sempre`,
  `mi chiedo se la tua domanda abbia abbassato la temperatura del mio cervello di qualche grado`,
  `se la tua domanda fosse un piatto, sarebbe sicuramente un insipido pasticcio di stupidità`,
  `spero che tu abbia assicurato la tua domanda, perché è un vero rischio per l'intelligenza`,
  `la tua domanda ha appena abbassato il valore intellettuale del nostro universo`,
  `hai mai pensato che la tua domanda potrebbe essere la causa del riscaldamento globale dell'intelligenza?`,
  `spero che tu non abbia intenzione di tramandare la tua domanda alle future generazioni, altrimenti sarà un'epidemia di stupidità`,
  `la tua domanda ha appena reso la teoria dell'evoluzione un po' più difficile da credere`,
  `mi chiedo se la tua domanda abbia appena causato un black out nel cervello di qualcuno`,
  `spero che la tua domanda non sia una rappresentazione accurata del tuo pensiero quotidiano, altrimenti è un po' preoccupante`,
  `la tua domanda ha appena fatto un buco nero nell'intelligenza collettiva dell'umanità`,
  `mi chiedo se la tua domanda sia stata un tentativo di comunicazione con una forma di vita aliena, perché di certo non sembrava rivolta a questo pianeta`,
  `spero che tu non abbia intenzione di scrivere un libro basato su quella domanda, altrimenti sarà una lettura molto breve`,
  `la tua domanda mi ha fatto desiderare di poter aprire un portale verso un universo parallelo dove non esisti`,
  `hai mai pensato che la tua domanda potrebbe essere la prova definitiva che viviamo in una simulazione?`,
  `spero che tu non abbia intenzione di continuare a fare domande, altrimenti mi costringerai a chiedere un congedo per motivi di salute mentale`,
  `la tua domanda ha appena infranto il record mondiale di quanto possa essere assurda`,
  `mi chiedo se la tua domanda abbia appena violato una qualche legge universale della logica`,
  `spero che la tua domanda non sia l'inizio di una serie di domande altrettanto inutili, altrimenti mi ritroverò a dover rispondere a domande esistenziali come "Qual è il senso della vita?" o "Esiste vita su Marte?"`,
  `la tua domanda mi ha fatto desiderare di poter chiudere gli occhi e sperare che fosse solo un brutto sogno`,
  `hai mai pensato che la tua domanda potrebbe essere la chiave per risolvere i misteri dell'universo? No? Nemmeno io`,
  `spero che la tua domanda non sia stata una tentata esibizione di intelligenza, perché ha fallito miseramente`,
  `mi chiedo se la tua domanda abbia appena fatto piangere un bambino di pochi mesi per l'incertezza del suo futuro intellettuale`,
  `spero che tu non abbia intenzione di fare carriera nell'ambito delle domande stupide, perché è un settore molto competitivo`,
  `la tua domanda ha appena fatto implodere il mio concetto di realtà`,
  `mi chiedo se la tua domanda sia stata la causa principale della scomparsa dei dinosauri`,
  `spero che tu abbia un buon motivo per aver fatto quella domanda, altrimenti è un po' triste`,
  `hai mai pensato che la tua domanda potrebbe essere la prova che siamo soli nell'universo?`,
  `spero che la tua domanda non sia stata il risultato di un'intuizione, altrimenti mi dispiace per te`,
  `mi chiedo se la tua domanda abbia appena aperto un portale verso un'altra dimensione di stupidità`,
  `spero che tu non abbia intenzione di scrivermi ancora in futuro, perché non credo di poter sopportare un'altra domanda del genere`,
  `la tua domanda ha appena fatto sì che un grido di disperazione risuonasse nell'universo`,
  `hai mai pensato che la tua domanda potrebbe essere stata la causa dell'estinzione dei Neanderthal?`,
  `spero che la tua domanda non sia stata la causa di un'anomalia temporale che ci ha portato a questo momento di confusione cosmica`,
  `mi chiedo se la tua domanda sia stata il risultato di una scommessa persa, perché non riesco a trovare un'altra spiegazione plausibile`,
  `spero che tu non abbia intenzione di fare domande simili in futuro, perché è dannoso per la salute mentale di chi le legge`,
  `la tua domanda ha appena messo in discussione la mia fede nell'intelligenza umana`,
  `mi chiedo se la tua domanda abbia appena fatto impazzire un computer in qualche luogo remoto`,
  ];

  const uniqueResponses = [...new Set(responses)];
  const randomResponse = uniqueResponses[Math.floor(Math.random() * uniqueResponses.length)];

  m.reply(randomResponse.trim(), null, m.mentionedJid ? { mentions: m.mentionedJid } : {});
};

handler.customPrefix = /come/i;
handler.command = new RegExp;

export default handler;