const handler = async (m, { command, text }) => {
  const responses = [
    `si`,
    `no`,
    `impossibile`,
    `secondo me no`,
    `e io che cavolo ne so`,
    `secondo me si`,
    `SI`,
    `è una stronzata`,
    `saresti un coglione se non lo facessi`,
    `devi farlo assolutamente`,
    `anche secondo me`,
    `provaci`,
    `per me è la cipolla`,
    `non ho capito bene, ripeti`,
    `AHAHAHAH`,
    `può darsi`,
    `ma chi lo sa`,
    `certamente no`,
    `senza dubbio`,
    `mai e poi mai`,
    `non ne sono sicuro`,
    `chiedilo a tua nonna`,
    `io dico di sì`,
    `assolutamente no`,
    `in teoria sì`,
    `dubito fortemente`,
    `chi lo sa`,
    `potrebbe essere`,
    `non ne vale la pena`,
    `nessun commento`,
    `non lo farei se fossi in te`,
    `ti conviene pensarci bene`,
    `non ne sono convinto`,
    `meglio di no`,
    `hai pensato di chiedere a qualcun altro?`,
    `non c'è speranza`,
    `sicuramente`,
    `probabilmente no`,
    `senza ombra di dubbio`,
    `impossibile da dire`,
    `non scommetterei su questo`,
    `non ho la minima idea`,
    `non sono sicuro di poterti aiutare`,
    `meglio cercare altrove`,
    `puoi provarci, ma non garantisco niente`,
    `è complicato`,
    `non ci contare troppo`,
    `dubito fortemente`,
    `forse`,
    `è difficile dirlo`,
    `ne dubito`,
    `non penso proprio`,
    `mai nella vita`,
    `non ci scommetterei`,
    `improbabile`,
    `non vedo come`,
    `non ne sono convinto`,
    `non ne ho idea`,
    `non ne sono sicuro`,
    `ho i miei dubbi`,
    `non lo farei se fossi in te`,
    `è una possibilità`,
    `neanche per sogno`,
    `non vale la pena provarci`,
    `non lo so con certezza`,
    `potrebbe andare in entrambi i modi`,
    `sembra difficile`,
    `non posso rispondere a questa`,
    `non ti darei molte speranze`,
    `non ci metterei la mano sul fuoco`,
    `non credo proprio`,
    `è una scommessa azzardata`,
    `è rischioso`,
    `non ci scommetterei la casa`,
    `ho i miei dubbi`,
    `non posso dirtelo con certezza`,
    `non è garantito`,
    `dipende da molti fattori`,
    `potrebbe essere un'opzione`,
    `non ne sono sicuro`,
    `non lo vedo probabile`,
    `non metterei le mani sul fuoco`,
    `è incerto`,
    `non lo sappiamo fino a quando non succede`,
    `non lo escluderei a priori`,
    `non è fuori discussione`,
    `non saprei dirtelo`
  ];

  const randomResponse = responses[Math.floor(Math.random() * responses.length)];

  m.reply(randomResponse.trim(), null, m.mentionedJid ? { mentions: m.mentionedJid } : {});
};

handler.customPrefix = /secondo|cosa|parere|opinione|pareri|devo/i;
handler.command = new RegExp;

export default handler;